config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'
  get 'register', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  resources :posts, except: [:destroy] do
    member do 
      post :vote
    end
    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end
  resources :categories, only: [:create, :show, :new]
  resources :users, only: [:show, :create, :edit, :update]
end

app/models/category.rb
class Category < ActiveRecord::Base
  include Sluggable
  has_many :post_categories
  has_many :posts, through: :post_categories

  validates :name, presence: true, uniqueness: true

  sluggable_column :name

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Voteable
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :post

  validates :body, presence: true

end

app/models/post.rb
class Post < ActiveRecord::Base
  include Voteable
  include Sluggable
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories
  validates :title, :description, presence: true

  sluggable_column :title
end

app/models/user.rb
class User < ActiveRecord::Base
  include Sluggable
  has_many :posts
  has_many :comments
  has_many :votes

  has_secure_password validations: false

  validates :username, presence: true, length: {minimum:3}, uniqueness: true
  validates :password, presence: true, length: {minimum:6}, on: :create

  sluggable_column :username

  def admin?
    self.role == 'admin'
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :voteable, polymorphic: true

  validates_uniqueness_of :user, scope: [:voteable_type, :voteable_id]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?, :require_creator

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You have to log in to do that."
      redirect_to root_path
    end
  end

  def require_admin
    access_denied unless logged_in? && current_user.admin?
  end

  def access_denied
    flash[:error] = "You can't do that."
    redirect_to root_path
  end

  def require_creator
    access_denied unless logged_in? && (current_user == @post.creator || current_user.admin?)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_user, only: [:new, :create]
  before_action :require_admin, only: [:new, :create]

  def show
    @category = Category.find_by slug: params[:id]
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    
    if @category.save
      flash[:notice] = 'New category created!'
      redirect_to root_path
    else
      render 'new'
    end
  end

  private
  def category_params
    params.require(:category).permit!
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  before_action :require_user
  
  def create
    @comment = Comment.new(comment_params)
    @comment.creator = current_user
    @post = Post.find_by slug: params[:post_id]
    @comment.post = @post
    if @comment.save
      flash[:notice] = 'New comment added!'
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end

  def vote
    @post = Post.find_by slug: params[:post_id]
    @comment = @post.comments.find(params[:id])
    @vote = Vote.create(user: current_user, vote: params[:vote], voteable: @comment)
    respond_to do |format|
      format.html do
        if @vote.valid?
          flash[:notice] = "Your vote is counted."
        else
          flash[:error] = "You've already voted."
        end
        redirect_to :back
      end
      format.js

    end
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:show, :index, :vote]
  before_action :require_creator, only: [:edit, :update]

  def index
    @posts = Post.all.sort_by{|x| x.total_votes}.reverse
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.all
  end

  def new
    @post = Post.new
  end

  def create

    @post = Post.new(post_params)
    @post.creator = current_user

    if @post.save
      flash[:notice] = "Your post is created."
      redirect_to post_path(@post) 
    else
      render 'new'
    end
  end

  def edit
  end

  def update

    if @post.update(post_params)
      flash[:notice] = "Your post is updated."
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def vote
    @vote = Vote.create(user: current_user, voteable: @post, vote: params[:vote])
    respond_to do |format|
      format.html do
        if @vote.valid?
          flash[:notice] = "Your vote is counted."
        else
          flash[:error] = "You have already voted."
        end
        redirect_to :back
      end

      format.js
    end
  end

  private
  def post_params
    params.require(:post).permit!
  end

  def set_post
    @post = Post.find_by slug: params[:id]
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:username])
    # alternatively, user = User.where(username: params[:username]).first
    # because User.where gives an array

    if user && user.authenticate(params[:password])
      # save user id not user because cookie has size limit
      session[:user_id] = user.id
      flash[:notice] = 'You are now logged in.'
      redirect_to root_path
    else
      flash.now[:notice] = 'There is something wrong with your username and password. Try again or register <a href="/register">here</a>'.html_safe
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've logged out."
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def show
  end

  def new
    @user = User.new
  end

  def create

    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Your account is successfully created!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Profile updated."
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :time_zone)
  end

  def set_user
    @user = User.find_by slug: params[:id]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_time(dt)
    if logged_in? && !current_user.time_zone.blank?
      dt = dt.in_time_zone(current_user.time_zone)
    end
    dt.strftime("%A, %b %-d, %Y %l:%M%P %Z")
  end
end

app/views/categories/_category.html.erb
<span class='badge'><%= link_to category.name, category_path(category) %></span>

app/views/categories/new.html.erb
<%= render 'shared/content_title', title: 'Create a New Category' %>
<%= render 'shared/display_errors', obj: @category %>

<div class='well'>
  <%= form_for @category do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br/>
    <%= f.submit(class: 'btn btn-primary') %>
  <% end %>
</div>

app/views/categories/show.html.erb
<h1>
  <ol class='breadcrumb'>
    <li><%= link_to "All Posts", root_path %></li>
    <li class='active'><%= @category.name %></li>
  </ol>
</h1>
<hr/>

<% @category.posts.each do |post| %>
<%= render 'posts/post', post: post%>
<% end %>

app/views/comments/_comment.html.erb
<% show_post ||= false %>


<div class='row'>
  <div class='span0 well text-center'>
        <% if logged_in? %>
        <%= link_to vote_post_comment_path(comment.post, comment, vote: true), method: 'post', remote: true do %>
        <span class="glyphicon glyphicon-chevron-up"></span>
        <% end %>
    <% else %>
    <span class="glyphicon glyphicon-chevron-up"></span>
    <% end %>
    <br/>
        <span id='comment_<%= comment.id %>_vote'><%= comment.total_votes %></span>
    <br/>
    <% if logged_in? %>
        <%= link_to vote_post_comment_path(comment.post, comment, vote: false), method: 'post', remote: true do %>
        <span class="glyphicon glyphicon-chevron-down"></span>
        <% end %>
    <% else %>
    <span class="glyphicon glyphicon-chevron-down"></span>
    <% end %>
  </div>

  <div class='well span8'>
    <em><%= comment.body %></em>
    <% if show_post %>
    on <%= link_to comment.post.title, post_path(comment.post) %>
    <% end %>
    <br/>
    <p>by <%= link_to comment.creator.username, user_path(comment.creator) %> on <%= format_time(comment.created_at) %></p>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
</ul>
<div class='navbar-nav'>
  <% if logged_in? %>
    <%= link_to 'New Post', new_post_path, :class => 'btn btn-success' %>
  <% end %>
  <div class='btn-group'>
    <button href="#" class="dropdown-toggle btn btn-default" data-toggle="dropdown" role="button" aria-expanded="false">Category <span class="caret"></span></button>
    <ul class="dropdown-menu" role="menu">
      <% Category.all.each do |category| %>
      <li><%= link_to category.name, category_path(category) %></li>
      <% end %>
      <% if logged_in? && current_user.admin? %>
        <li class='divider'></li>
        <li><%= link_to 'New Category', new_category_path%></li>
      <% end %>
    </ul>
  </div>
</div>

<div class='navbar-nav navbar-right'>
  <% if !logged_in? %>
    <%= link_to "Register", '/register', :class => 'btn btn-success' %>
    <%= link_to "Log In", '/login', :class => 'btn navbar-btn' %>
  <% else %>
    <div class='btn-group'>
      <button class="dropdown-toggle btn btn-default" data-toggle='dropdown' role='button' aria-expanded='false'><span class='glyphicon glyphicon-user'></span> <%= current_user.username %> <span class='caret'></span></button>
      <ul class='dropdown-menu' role='menu'>
        <li><%= link_to 'View Profile', user_path(current_user) %></li>
        <li><%= link_to 'Edit Profile', edit_user_path(current_user) %></li>
      </ul>
    </div>
      <span data-toggle='popover' data-placement='bottom' data-content='Log Out' data-trigger="hover" id='logout'><%= link_to "<span class='glyphicon glyphicon-log-out'></span>".html_safe, '/logout' %></span>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_form.html.erb
<%= render 'shared/display_errors', obj: @post %>

<div class='well'>
  <%= form_for @post do |f| %>
    <div class='contol-group'>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>

    <div class='contol-group'>
        <%= f.label :url %>
        <%= f.text_field :url %>
    </div>

    <div class='contol-group'>
        <%= f.label :description %>
        <%= f.text_area :description, rows: 8 %>
    </div>

    <!-- option 1: checkboxes helper -->
    <div class='control-group'>
      <%= f.label 'Categories' %>
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
        <% cb.label(class: 'checkbox-inline') {cb.check_box(class: 'checkbox') + cb.text} %>
      <% end %>
    </div>

    <!-- option 2: HTML select boxes
    <div class='control-group'>
      <select name='post[category_ids][]' multiple='multiple'>
        <% Category.all.each do |category| %>
          <option value= '<% "#{category.id}" %>' > <%= "#{category.name}" %></option>
        <% end %>
      </select>
    </div>
    -->
    <br/>
    <%= f.submit(@post.new_record? ? "Create post!" : "Update post!" , class: 'btn btn-primary')%>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class='container-fluid'>
  <div class='row'>
    <% if logged_in? %>
    <div class='col-sm-1'>
      <div class='span0 well text-center'>
        <% if logged_in? %>
          <%= link_to vote_post_path(post, vote: true), method: 'post', remote: true do %>
            <span class="glyphicon glyphicon-chevron-up"></span>
          <% end %>
        <% else %>
          <span class="glyphicon glyphicon-chevron-up"></span>
        <% end %>
        <br/>
        <span id='post_<%= post.slug %>_vote'><%= post.total_votes %></span>
        <br/>
        <% if logged_in? %>
          <%= link_to vote_post_path(post, vote: false), method: 'post', remote: true do %>
            <span class="glyphicon glyphicon-chevron-down"></span>
          <% end %>
        <% else %>
          <span class="glyphicon glyphicon-chevron-down"></span>
        <% end %>
      </div>
    </div>
    <% end %>
    

    <div class='col-sm-11'>
      <div class='panel panel-default'>
        <div class='panel-heading'>
          <div class='panel-title'>
            <h3><%= link_to post.title, post_path(post) %>
              <% if logged_in? && current_user == post.creator %>
                <small>[<%= link_to "edit", edit_post_path(post) %>]</small>
              <% end %>
            </h3>
          </div>
          <%= render post.categories %>
        </div>
        <div class='panel-body'>
          <p><%= post.description %></p>
          <!--display post related info-->
          <p class='quiet'>Posted by <%= link_to post.creator.username, user_path(post.creator) %> on <%= format_time(post.created_at) %></p>
          <!--edit and display number of comments-->
          <p><%= link_to "#{post.comments.size} " + "#{post.comments.size <= 1 ? 'comment' : 'comments'}", post_path(post)%></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: 'Edit This Post' %>

<%= render 'form' %>

app/views/posts/index.html.erb
  <%= render 'shared/content_title', title: 'All Posts' %>

<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: 'Create a New Post' %>


<%= render 'form' %>

app/views/posts/show.html.erb
<% render @post.categories %>
<!--if no user for post, show 'anonymous'-->
<%= render 'shared/content_title', title: @post.title, author: (@post.creator.username rescue 'anonymous') %>



<%= @post.description %>
<hr/>
<p align='left'><small>Posted on <%= format_time(@post.created_at) %> // Last updated on <%= format_time(@post.updated_at) %></small></p>
<p align='right'>
  <% if logged_in? && (current_user == @post.creator || current_user.admin?) %>
    <small float='right'>[<%= link_to "edit this post", edit_post_path(@post) %>]</small> 
  <% end %>
  <small float='right'>[<%= link_to "back to All Posts", posts_path %>]</small>
</p>

<% if logged_in? %>
  <%= render 'shared/display_errors', obj: @comment %>
  <%= form_for [@post, @comment] do |f| %>
    <%= f.label :body, 'Leave a Comment' %>
    <%= f.text_area :body, rows: 3, class: 'span4' %>
    <br/>
    <%= f.submit(class: 'btn btn-primary')%>
  <% end %>
<% end %>

<h4> Comments: </h4>

<%= render @post.comments %>
<% if @post.comments.size == 0 %>
  <em>No discussion yet.</em>
<% end %>

app/views/shared/_content_title.html.erb
<div>
  <h1><%= title %> <small><%= "by #{author}" if not defined?(author).nil? %></small></h1>

  <hr/>
  
</div>

app/views/shared/_display_errors.html.erb
<% if obj.errors.any? %>
  <div class='alert alert-danger'>
    <p>Please fix the following error(s):</p>
    <ul style = "list-style: none;">
      <% obj.errors.full_messages.each do |msg| %>
        <li><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <span><%= msg %></span>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_profile.html.erb
<div class='well'>
  <%= form_for @user do |f| %>
    <div class='control-group'>
      <%= f.label :username %>
      <%= f.text_field :username %>
    </div>

    <div class='control-group'>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>

    <div class='control-group'>
      <%= f.label :time_zone %>
      <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, default: Time.zone.name %>
    </div>

    <div class='control-group'>
      <%= f.submit @user.new_record? ? 'Register' : 'Update', class: 'btn btn-primary'%>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= render 'shared/content_title', title: 'Edit User' %>

<%= render 'profile' %>

app/views/users/new.html.erb
<%= render 'shared/content_title', title: 'Register' %>

<%= render 'shared/display_errors', obj: @user %>
<%= render 'profile' %>

app/views/users/show.html.erb
<%= render 'shared/content_title', title: 'User Profile' %>

<div class='well'>
  <p><strong>Username</strong>: <%= @user.username %></p>
  <p><strong>Password</strong>: [hidden] <%= link_to 'edit', edit_user_path(@user) %></p>
  <p><strong>Time Zond</strong>: <%= @user.time_zone %>
</div>

Recent activities:
  <!-- Tab panes -->
<ul class="nav nav-tabs">
  <li role="presentation" class="active"><a href="#posts" data-toggle='tab'>Posts</a>
  </li>
  <li role="presentation"><a href="#comments" data-toggle='tab'>Comments</a>
  </li>
</ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane fade in active" id="posts">
      <% @user.posts.each do |post| %>
        <%= render 'posts/post', post: post %>
      <% end %>
      <% if @user.posts.size == 0 %>
        <em><%= @user.username %> has not posted anything yet.</em>
      <% end %>
    </div>
    <div role="tabpanel" class="tab-pane fade" id="comments">
      <%= render @user.comments, show_post: true %>
      <% if @user.comments.size == 0 %>
        <em>No comments.</em>
      <% end %>
    </div>

  </div>